name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker image
      run: |
        docker build -t nazwa_uzytkownika/repozytorium:${{ github.sha }} .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push nazwa_uzytkownika/repozytorium:${{ github.sha }}
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
    - name: Update deployment with new image
      run: |
        kubectl set image deployment/hello-world-deployment hello-world=nazwa_uzytkownika/repozytorium:${{ github.sha }}
